language: node_js
before_install:
  touch .env;
  if [ $IS_INTEGRATION_TEST ]; then rvm install ruby-2.4.3 --binary && rvm use ruby-2.4.3 && bundle install; else echo "Not an integration test. Skipping Ruby setup"; fi
script: npm run $TEST
addons:
  sauce_connect: true
  hosts:
    - bt.local
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
env:
  matrix:
    # - TEST="lint"
    # - TEST="test:unit"
    - TEST="test:integration" IS_INTEGRATION_TEST=true
  global:
  - secure: SvjZyrdqFJBWCgduVObookkrTLIer/OF4yILB5uy5DuzDT52vmUGLKWj1Zjevy6PKdoZ3QPdrbrEn8tIRuiiTCbBTi9X3X8cQjVHN1Jxq1w/TIUiCxg1Wt+M+FnS2EamLMo2BFEsCM5qXrLwUd23uLXxMRJKDikBvaq1Lgib+S3CDhROORgEtnZeXXd328NiUNriDadhnC7kTACZ16Urt9ZrTJrXwQLujNJlO/zVxB0dBTV8Hzjp/Qce/D3XFg943xeHj7UuffF9ntcJqGEImY226VVWwk3D78j9zpfOXCIBJD/h/uls77eZzSi/9o2voVqfWHGuuKoRfVC8772kuWoe95Fm8ntFUbEWutDnfhs7aMqSW4rYMbFUSMqf6qBGWse07clk6zx0cZpsC1vscf3QSDQu/joj8ohX6+1Qn4gd+1/Rp3WjLBdWUcTfcODLspahwXZ5xnkzU04m46eO23E++U6WYD22xJnHZVsWHM+aGcDRQYFg07mnzOQwSUs66qXpMLCiL4vFiZ4tTehzTD3iMNF+3cr8WDlgFUH9rNBJjzYJeCOycdxwQg9f7orh/Iwm8TdcWQAxpXaWdfa6KidY/4fDi7gCCoxePjuDHnDXt8e+xlMYIM3fy+xfHb7GWCyGnHdQRxLEPFSTPnTDyWVcg7CSbGl9YmqMRa7SMus=
  - secure: u5obPww8nFh3zcov6B9jBj/7LldTT+jOWOUQv/MxE65G6dFWhyJIiNSG/f7HtYr/ziY77B5a+SIoYd097G5lqrtMj128cCGvamdXye0d3YzrbtVGiN7wS3cXPlRPORcaPhQkRl4tQPsElj742f9FRWXsXLdGDzmpPAJDO0lBk9SZuRfdNvw9nTvoHHZgQxu2/lHaMie6v2B3iXSgmgtTN5r6qXXlDoCxZlCB+4cVY2SVNAwXoNk3DDBYsWdOAzVWaOO28l1NaH5CAoKHpz9x1YjjOdHBER5mG2EogQ5Mo4/CAsO9VuEL5Mp0sfhEG7tPXdM0GktFxiRSGfYGIbaMkRUA2npwhj0cWBPdPGaMTQHZI/anr8VHaxUlEP84gXw8VvavttBpaDS/Wdz5dIy5cbqB2q3xhE0VGaR2fG39O/MA+Oq89ZUhThgS8YqltMOKe5AYM3nIeQje61NUpb7FC5q6VLuIKVfSyak2r+TFSVdI27DwU8/QrTIItl1yYJh9eASMX2VIudUahxz0twK7jXuLc9zYtOHgH4bty997G1Z/sr7vu6upyz6081p2tdPDWXzSVIU0HfLj8wRCFnvI8rkKOWfJUGg8ikKJcWoJON3Q59LiuqnEafDiehUnnuueHw5FRi8gcmw82PvFxtoQLzIxfPPNy8k7P2ghsormLjU=
